### ISSUE TITLE
Generated properties not included in SourcesSets

### ISSUE THREAD

**Issue by pell-je** [graphql-java-generator/GraphQL-Forum-Gradle-Tutorial-client#2]
/build/generated/resources/graphqlGradlePlugin not included in SourcesSets

The ReadMe has this:
`sourceSets.main.java.srcDirs += '/build/generated/resources/graphqlGradlePlugin'`

but needs to be 
`sourceSets.main.resources.srcDirs += '/build/generated/resources/graphqlGradlePlugin'`

**Comment by etienne-sf** [comment]
I'm finishing a release for the plugin, and I will update the tutorial.

Thanks for the report
